<?php
# This file was automatically generated by the MediaWiki 1.24.1
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}

## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename = "SDSC MVP MediaWiki";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## https://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath = "/MediaWiki";
$wgScriptExtension = ".php";

## The protocol and server name to use in fully-qualified URLs
$wgServer = "https://holonet2.sdsc.edu";

## The relative URL path to the skins directory
$wgStylePath = "$wgScriptPath/skins";

## The relative URL path to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogo = "$wgScriptPath/resources/assets/SDSCLogo.png";

## UPO means: this is also a user preference option

$wgEnableEmail = false;
$wgEnableUserEmail = true; # UPO

$wgEmergencyContact = "apache@holonet.sdsc.edu";
$wgPasswordSender = "apache@holonet.sdsc.edu";

$wgEnotifUserTalk = false; # UPO
$wgEnotifWatchlist = false; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype = "sqlite";
$wgDBserver = "";
$wgDBname = "mediawiki";
$wgDBuser = "";
$wgDBpassword = "";

# SQLite-specific settings
$wgSQLiteDataDir = "/var/lib/mediawiki";

## Shared memory settings
$wgMainCacheType = CACHE_NONE;
$wgMemCachedServers = array();

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads = true;
#$wgUseImageMagick = true;
#$wgImageMagickConvertCommand = "/usr/bin/convert";

# InstantCommons allows wiki to use images from http://commons.wikimedia.org
$wgUseInstantCommons = false;

## If you use ImageMagick (or any other shell command) on a
## Linux server, this will need to be set to the name of an
## available UTF-8 locale
$wgShellLocale = "en_US.utf8";

## If you want to use image uploads under safe mode,
## create the directories images/archive, images/thumb and
## images/temp, and make them all writable. Then uncomment
## this, if it's not already uncommented:
#$wgHashedUploadDirectory = false;

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publically accessible from the web.
#$wgCacheDirectory = "$IP/cache";

# Site language code, should be one of the list in ./languages/Names.php
$wgLanguageCode = "en";

$wgSecretKey = "1e14b6d0bef35e419031042604af2a8e2083d2d827d2794dae6d2ea7208064cb";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = "fe755fb1fa2a02b8";

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "";
$wgRightsText = "";
$wgRightsIcon = "";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "/usr/bin/diff3";

# The following permissions were set based on your choice in the installer
$wgGroupPermissions['*']['createaccount'] = false;
$wgGroupPermissions['*']['edit'] = false;
$wgGroupPermissions['*']['read'] = false;

## Default skin: you can change the default skin. Use the internal symbolic
## names, ie 'vector', 'monobook':
$wgDefaultSkin = "vector";

# Enabled skins.
# The following skins were automatically enabled:
require_once "$IP/skins/CologneBlue/CologneBlue.php";
require_once "$IP/skins/Modern/Modern.php";
require_once "$IP/skins/MonoBook/MonoBook.php";
require_once "$IP/skins/Vector/Vector.php";


# Enabled Extensions. Most extensions are enabled by including the base extension file here
# but check specific extension documentation for more details
# The following extensions were automatically enabled:
require_once "$IP/extensions/Cite/Cite.php";
# require_once "$IP/extensions/ConfirmEdit/ConfirmEdit.php";
# require_once "$IP/extensions/Gadgets/Gadgets.php";
require_once "$IP/extensions/ImageMap/ImageMap.php";
# require_once "$IP/extensions/InputBox/InputBox.php";
require_once "$IP/extensions/LdapAuthentication/LdapAuthentication.php";
# require_once "$IP/extensions/SyntaxHighlight_GeSHi/SyntaxHighlight_GeSHi.php";
require_once "$IP/extensions/WikiEditor/WikiEditor.php";


# End of automatically generated settings.
# Add more configuration options below.



$wgDefaultUserOptions['usebetatoolbar'] = 1;
$wgDefaultUserOptions['usebetatoolbar-cgd'] = 1;
$wgDefaultUserOptions['wikieditor-preview'] = 1;
$wgDefaultUserOptions['wikieditor-publish'] = 1;

$wgFavicon = "$wgScriptPath/favicon.ico";


require_once "$IP/extensions/MultimediaViewer/MultimediaViewer.php";
require_once "$IP/extensions/CommonsMetadata/CommonsMetadata.php";
require_once "$IP/extensions/EmbedPDF.php";
require_once "$IP/extensions/Math/Math.php";
require_once "$IP/extensions/SelectCategory/SelectCategory.php";

# Upload Configuration ############
wfLoadExtension('MsUpload');
$wgEnableWriteAPI = true; # enable the API
$wgEnableUploads = true; # enable uploads
$wgAllowJavaUploads = true; # Solves problem with Office 2007 and newer files (docx, xlsx, etc.)
$wgGroupPermissions['user']['upload'] = true;








# End Upload Configuration ###############

# ALL LDAP STUFF###################
require_once 'extensions/LdapAuthentication/LdapAuthentication.php';
require_once 'includes/AuthPlugin.php';
$wgAuth = new LdapAuthenticationPlugin();

$wgLDAPDomainNames = array(
        'ad.ucsd.edu'
);
$wgLDAPServerNames = array(
        'ad.ucsd.edu' => 'ldap.ad.ucsd.edu'
);

$wgLDAPUseLocal = false;

$wgLDAPEncryptionType = array(
        'ad.ucsd.edu' => 'ssl'
);

$wgLDAPProxyAgent = array(
	'ad.ucsd.edu' => 'cn=LDAP Access,ou=Service Account,ou=ITS,ou=SDSC,dc=ad,dc=ucsd,dc=edu'
);

$wgLDAPProxyAgentPassword = array(
	'ad.ucsd.edu' => 'ke*&b!e5$cuWRe7'
);

$wgLDAPBaseDNs = array(
        'ad.ucsd.edu' => 'ou=SDSC,dc=ad,dc=ucsd,dc=edu'
);

$wgLDAPSearchAttributes = array(
        'ad.ucsd.edu' => 'sAMAccountName'
);


$wgLDAPGroupUseFullDN = array( "ad.ucsd.edu"=>true );

$wgLDAPGroupObjectclass = array( "ad.ucsd.edu"=>"group" );

$wgLDAPGroupAttribute = array( "ad.ucsd.edu"=>"member" );

$wgLDAPGroupSearchNestedGroups = array( "ad.ucsd.edu"=>true );

$wgLDAPGroupNameAttribute = array( "ad.ucsd.edu"=>"cn" );

$wgLDAPRequiredGroups = array( 
	"ad.ucsd.edu"=>array(
		"cn=SDSC-ITSS,ou=Groups,ou=SDSC,dc=ad,dc=ucsd,dc=edu"
	)
);

$wgLDAPActiveDirectory = array( "ad.ucsd.edu"=>true );

$wgLDAPLowerCaseUsername = array(
        'ad.ucsd.edu' => true
);

$wgShowExceptionDetails = true;
$wgShowSQLErrors = 1;


########################
$wgLDAPUseLDAPGroups = array(
	'ad.ucsd.edu' => true
);

# Create the mvp group, and give it sys rights
$wgGroupPermissions['mvp'] = $wgGroupPermissions['sysop'];
$wgGroupPermissions['sdsc-itss'] = $wgGroupPermissions['user'];

# $wgImplicitGroups ignores these groups in MediaWiki
$wgImplicitGroups[] = "sdsc-print-users";
$wgImplicitGroups[] = "sdsc-citrix-users";
$wgImplicitGroups[] = "sdsc-it-support";
$wgImplicitGroups[] = "sdsc-remote-desktop-users";
$wgImplicitGroups[] = "sdsc-wikiusers";
$wgImplicitGroups[] = "sdsc-windows-core";
$wgImplicitGroups[] = "reportinggroup {54ba3815-8296-40c3-a0eb-656e428dca2d}";


# Allow the following file extensions to be uploaded to MediaWiki
$wgFileExtensions = array( 'png', 'gif', 'jpg', 'jpeg', 'docx', 'xls', 'pdf', 'xlsx', 'zip'
);


$wgExternalLinkTarget = '_blank';
