#image: golang:1.10.3-stretch
image: alpine:latest

before_script:
  - pwd
  - uname -a
  - whoami

  - GITLAB_TOKEN=""
  - GITLAB_USERNAME=""

stages:
  - build
  - deploy

build site:
    stage: build
    image: gitlab.sdsc.edu:4567/j2dangelo/docker-devops:latest
    variables:
      DOCKER_HOST: tcp://localhost:2375
    services:
      - docker:dind
    script:
      - docker info
      - docker login -u ${GITLAB_USERNAME} -p ${GITLAB_TOKEN} gitlab.sdsc.edu:4567
      - docker build -f ./manifests/Dockerfile . -t gitlab.sdsc.edu:4567/aha/holonet-sdnap:latest
      - docker push gitlab.sdsc.edu:4567/aha/holonet-sdnap:latest
      
deploy cluster:
    stage: deploy
    image: gitlab.sdsc.edu:4567/j2dangelo/docker-devops:latest
    variables:
      DOCKER_HOST: tcp://localhost:2375
      KUBERNETES_SERVICE_ACCOUNT_OVERWRITE: admin-user
    services:
      - docker:dind
    script:
      - ls -al
      - ./manifests/configmap-create.sh
      - docker info
      - docker login -u ${GITLAB_USERNAME} -p ${GITLAB_TOKEN} gitlab.sdsc.edu:4567
      - kubectl version
      - kubectl cluster-info
      - kubectl get node
#      - kubectl -n jx delete deployment sdnap
      - kubectl apply -f ./manifests/hostpath-pv.yaml --record
      - kubectl apply -f ./manifests/hostpath-pvc.yaml --record
      - kubectl apply -f ./manifests/confd-pv.yaml --record
      - kubectl apply -f ./manifests/confd-pvc.yaml --record
      - kubectl apply -f ./manifests/sdnap-deploy.yaml --record
        #- kubectl replace -f ./manifests/sdnap-deploy.yaml --record
      - kubectl apply -f ./manifests/sdnap-svc.yaml --record
      - kubectl apply -f ./manifests/sdnap-ing.yaml --record
      - kubectl -n jx patch deployment sdnap -p "{\"spec\":{\"template\":{\"metadata\":{\"annotations\":{\"date\":\"`date +'%s'`\"}}}}}"
