#version: '3.2'
version: '2.0'
services:
    mediawiki:
        container_name: sdsc-mediawiki
        build:
            context: .
            dockerfile: ./Dockerfile
# image pushed to repository [docker.io/sdscdocker/holo-mediawiki]
#        image: sdscdocker/mediawiki:latest
        image: gitlab.sdsc.edu:4567/aha/holonet:latest
        ports:
        - "80:80"

        command: ["apache2","-D","FOREGROUND"]
