kind:               PersistentVolume
apiVersion:         v1
metadata:
  name:             etc-pv
  namespace:        jx
  labels:
    type:           local
spec:
  storageClassName: etc
  capacity:
    storage:        1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path:           "/nfs/home/shared/ath038/sdnap/site/etc/httpd/conf/"
