kind:               PersistentVolumeClaim
apiVersion:         v1
metadata:
  name:             etc-pvc
  namespace:        jx
spec:
  storageClassName: etc
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage:      200Mi
