apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sdnap
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /sdnap
        backend:
          serviceName: sdnap
          servicePort: http


