apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: holonet
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: maersk.sdsc.edu
    http:
      paths:
      - path: /sdnap
        backend:
          serviceName: sdnap
          servicePort: http
      - path: /tasktracker
        backend:
          serviceName: tasktracker
          servicePort: http
      - path: /services
        backend:
          serviceName: services
          servicePort: http


