apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sdnap
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: sdnap.sdsc.edu
    http:
      paths:
      - path: /
        backend:
          serviceName: sdnap
          servicePort: http


