# ------------------- SDNAP Service ------------------- #
apiVersion: v1
kind: Service
metadata:
    name: sdnap
    namespace: jx
spec:
  ports:
  - name: http
    targetPort: 80
    port: 80
  - name: https
    targetPort: 443
    port: 443
  selector:
    app: sdnap
