# Configuration to deploy Holonet sites for POC
# Kubernetes 1.8.
#
# Example usage: kubectl create -f <this_file>
#

# ------------------- MediaWiki Deployment ------------------- #
apiVersion: apps/v1beta1
kind: Deployment
metadata:
    labels:
      app: sdnap
    name: sdnap
    namespace: jx
spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: sdnap
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
    minReadySeconds: 5
        
    template:
        metadata:
            labels:
                app: sdnap
                version: v0.4
        spec:
            containers:
            - name: sdnap
              image: gitlab.sdsc.edu:4567/aha/holonet-sdnap
              #image: bylexus/apache-php53
              imagePullPolicy: Always
              env:
                # The MySQL image will configure a root password with the value of MYSQL_ROOT_PASSWORD...
                - name: SQL_ROOT_PASSWORD
                  valueFrom:
                    # rather than embed sensitive details in this config
                    # we reference another Kubernetes object
                    # in this case, the Secret with the name: mysql-credentials
                    secretKeyRef:
                      name: holonet-credentials
                      # references the rootpw key-value pair from the mysql-credentials Secret
                      key: rootpw
                # ... an initial non-root user with a username of the value of MYSQL_USER ...
                - name: SQL_USER
                  valueFrom:
                    secretKeyRef:
                      name: holonet-credentials
                      key: user
                # ... and a password of the value of MYSQL_PASSWORD ...
                - name: SQL_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: holonet-credentials
                      key: password
                # ... and an initial database named sdnapdb
                # with the value of MYSQL_DATABASE (while granting MYSQL_USER superuser access.)
                - name: SQL_DATABASE
                  value: sdnapdb
                # use service name as host
                - name: SQL_HOST
                  value: sdnapdb.jx.svc.cluster.local

              ports: 
              - containerPort: 80
              volumeMounts:
              - mountPath: "/etc/apache2/sites-enabled/"
                name: apache2-config-volume

#              - mountPath: "/etc/apache2/conf.d"
#                subPath: "httpd.conf"
#                name: confd-volume
              - mountPath: "/etc/pki/tls/certs/maersk_sdsc_edu_cert.crt"
                name: cert-volume
                subPath: "maersk_sdsc_edu_cert.crt"
              - mountPath: "/etc/pki/tls/private/maersk.key"
                name: key-volume
                subPath: "maersk.key"
              - mountPath: "/etc/pki/tls/certs/maersk_sdsc_edu_interm.crt"
                name: interm-volume
                subPath: "maersk_sdsc_edu_interm.crt"
#              - mountPath: "/etc/php5/cli/php.ini"
#                name: php-config-volume 
#                subPath: "php.ini"
#             - mountPath: "/var/lib/mysql"
#               name: holonetcontent 
#               subPath: "var/lib/mysql"
#              - mountPath: "/var/lib/php"
#                name: holonetcontent 
#                subPath: "var/lib/php"
#  emptydir for sharing data between pods
#              - mountPath: "/var/lib"
#                name: workdir
              # Run commands in the containers
              command: ["/bin/bash","-c"]
              args:
                - echo starting;
                  echo "198.202.90.38  sdnap.sdsc.edu" >> /etc/hosts;
                  echo "198.202.90.38  services-sdsc.sdsc.edu" >> /etc/hosts;
                  echo "198.202.90.38  tasktracker.sdsc.edu" >> /etc/hosts;
                  echo "198.202.90.38  traefik.sdsc.edu" >> /etc/hosts;
                  echo "198.202.90.38  k8s.sdsc.edu" >> /etc/hosts;
                  ls /etc/apache2/sites-enabled;
                  ls /var/www;
                  echo "** cat /etc/apache2/apache2.conf **";
                  cat /etc/apache2/apache2.conf;
                  echo "** cat envvars **";
                  cat /etc/apache2/envvars;
                  echo "** cat httpd.conf **";
                  cat /etc/apache2/sites-enabled/httpd.conf;
                  cat /usr/local/bin/run;
                  echo "** source apache envvars **";
                  source /etc/apache2/envvars;
                  echo "** start apache2 **";
                  exec /usr/sbin/apache2 -DFOREGROUND;
                  #apachectl status;               

#            initContainers:
#              - name: chowns
#                image: busybox

#                command:
#                - chown
#                - "-R root:root"
#                - /work-dir/php
#                command:
#                - chown
#                - "-R root:root"
#                - /work-dir/mysql
#                command:
#                - chown
#                - "-R root:root"
#                - /work-dir/sdnap

            volumes:
#           - name: workdir
#             emptyDir: {}
#            - name: confd-hostpath
#              persistentVolumeClaim:
#                claimName: confd-pvc
#            - name: etc-hostpath
#             persistentVolumeClaim:
#                claimName: etc-pvc
            - name: apache2-config-volume
              configMap:
                name: apache2-config-sdnap  # generated from configmap-build.sh 
            - name: php-config-volume
              configMap:
                name: php-config-sdnap  # generated from  configmap-build.s
            - name: cert-volume
              configMap:
                name: cert-sdnap  
            - name: key-volume
              configMap:
                name: key-sdnap  
            - name: interm-volume
              configMap:
                name: interm-sdnap  # generated from configmap.yaml
                

---
