# ------------------- MW Service ------------------- #
apiVersion: v1
kind: Service
metadata:
    name: mediawiki
spec:
  ports:
    - nodePort: 32280
      port: 80
  selector:
    role: web-frontend
  type: NodePort

