# Configuration to deploy release version of the Dashboard UI compatible with
# Kubernetes 1.8.
#
# Example usage: kubectl create -f <this_file>
# ------------------- MediaWiki Deployment ------------------- #

---

apiVersion: v1
kind: ConfigMap
apiVersion: v1
metadata:
  name: mediawiki-config
  namespace: jx
data:
  mw-config-php.file: "site/etc/php.ini"
---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
    labels:
      k8s-app: mediawiki
    name: mediawiki
    namespace: jx
spec:
    replicas: 3
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        role: web-frontend
    template:
        metadata:
            labels:
                role: web-frontend
        spec:
            containers:
            - name: mediawiki
              image: sdscdocker/mediawiki:latest
              ports: 
              - containerPort: 80
              volumeMounts:
#              - mountPath: /etc
#                name: phpconf
              - mountPath: "/var/www/html"
                name: holonetcontent 
                subPath: "www"
#                subPath: "www/MediaWiki"
              - mountPath: "/var/lib/mediawiki"
                name: holonetcontent 
                subPath: "var/lib/mediawiki"
              - mountPath: "/var/lib/mysql"
                name: holonetcontent 
                subPath: "var/lib/mysql"
              - mountPath: "/var/lib/php"
                name: holonetcontent 
                subPath: "var/lib/php"
              - mountPath: "/etc/httpd"
                name: holonetcontent 
                subPath: "etc/httpd"
              - mountPath: "/etc/php.d"
                name: holonetcontent 
                subPath: "etc/php.d"
              - mountPath: "/etc/pki"
                name: holonetcontent 
                subPath: "etc/pki"
              - mountPath: "/var/lib"
                name: workdir

#            initContainers:
#              - name: chowns
#                image: busybox
#                command:
#                - chown
#                - "-R root:root"
#                - /work-dir/php
#                command:
#                - chown
#                - "-R root:root"
#                - /work-dir/mysql
#                command:
#                - chown
#                - "-R root:root"
#                - /work-dir/mediawiki
#                volumeMounts:
#                - name: workdir
#                  mountPath: "/work-dir"

            volumes:
            - name: workdir
              emptyDir: {}
            - name: holonetcontent
              persistentVolumeClaim:
                claimName: holonet-pvc
            - name: phpconf
              configMap:
                name: phpconfig  # generated from configmap-create.sh 

---
# ------------------- MW Service ------------------- #
apiVersion: v1
kind: Service
metadata:
    name: mediawiki
    namespace: jx
spec:
  ports:
  - name: http
    targetPort: 80
    port: 80
		selector:
			k8s-app: mediawiki
#  selector:
#    role: web-frontend


